// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLH6xDr2RonPrUUZbSEYqtg43OOi2L2A',
    appId: '1:55158109852:web:20ed231a99f2d1f66c1f59',
    messagingSenderId: '55158109852',
    projectId: 'tafaseer',
    authDomain: 'tafaseer.firebaseapp.com',
    storageBucket: 'tafaseer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl97CF0Apsqmv81auC-yPE9Zfr95cHqW0',
    appId: '1:55158109852:android:2d467a1ad82b8b7a6c1f59',
    messagingSenderId: '55158109852',
    projectId: 'tafaseer',
    storageBucket: 'tafaseer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQ9kQsi-1Vjm-jdbuaNhCgiTGKkXM3Xs',
    appId: '1:55158109852:ios:7cfcf2989571a7e86c1f59',
    messagingSenderId: '55158109852',
    projectId: 'tafaseer',
    storageBucket: 'tafaseer.firebasestorage.app',
    iosBundleId: 'com.tafaseer.tafaseerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQ9kQsi-1Vjm-jdbuaNhCgiTGKkXM3Xs',
    appId: '1:55158109852:ios:7cfcf2989571a7e86c1f59',
    messagingSenderId: '55158109852',
    projectId: 'tafaseer',
    storageBucket: 'tafaseer.firebasestorage.app',
    iosBundleId: 'com.tafaseer.tafaseerApp',
  );
}
